services:
  db:
    image: postgres:13
    restart: always
    container_name: stubby-integration-tests
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: local_test
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: stubby_test
